ON-15428: README.md for deployment with sample overlays
Xilinx-CNS/kubernetes-onload pull request #92
Opened 2023-12-01 17:22 UTC by pcolledg-amd

Deployment-focused README.md and sample overlays. I was not intending to add overlays so soon but it does make instructions super simple in comparison to what we had before.

I will shortly be integrating:
- [x] Link to forthcoming `config/samples/sfptpd/README.md`
- [ ] Updates from Day 0 addendum changes
- [x] Caveats (brief initial list only)
- [ ] Overlays suitable for our dev (optional, but probably easy)

The rest can come in subsequent commits. I'll harmonise with Release Notes, glaring differences only.

# Please ignore BUILD.md for now
It is untouched, I'll rebase it before merging.

2023-12-01 18:05 UTC, abower-amd requested changes
Some required changes identified but I like this.

2023-12-01 18:05 UTC, abower-amd commented on README.md
> +The cluster also requires access to the following node-specific kernel module container image(s) which may be provided externally or internally. If using in-cluster builds, push access to an internal
Last sentence is out of scope for the README - needs removing.

2023-12-04 15:03 UTC, jjay-xilinx reviewed
beside the nitpick of headings, readme looks fine

2023-12-05 09:40 UTC, abower-amd approved these changes
Great thanks, gives good shape.

2023-12-05 10:46 UTC, merged